### ISSUE TITLE
Compiled 5.1 Boot.img doesn't boots

### ISSUE THREAD

**Issue by muhammadfahadbaig** [olrak2/make_boot_image_hi6210sft#1]
Alright! I successfully compiled Image from 5.1.1 kernel sources using XePeleato's kernel source code. After making boot.img and flashing it (using your tool), phone is stuck on Huawei logo (no bootanimation, nothing). So what I am doing wrong now...

**Comment by olrak2** [comment]
Have you first installed the rom for android 5.1?

You first need to be on stock rom 5.1 and then you can flash your boot.img onto it.

Stock rom 5.1 you can find here : http://forum.xda-developers.com/p8lite/help/upgrade-android-5-1-1-b008-ale-21-t3285993

**Comment by muhammadfahadbaig** [comment]
Oops! Was a ramdisk issue. It's booting fine now!!! 
Also my device is not P8 Lite. It's Honor 4C which is based on same SoC as the P8 Lite. Thanks for everything.

**Comment by muhammadfahadbaig** [comment]
It's booting fine now... but don't close this issue yet... just wait...

**Comment by olrak2** [comment]
No problem :smile: Glad i could help.

**Comment by muhammadfahadbaig** [comment]
Ok.. Screen goes black after 5 minutes or so... Device is working as when I connect it to PC, it's identified.

**Comment by muhammadfahadbaig** [comment]
Let me explain that more closely. Screen goes black when I try to lock the phone. When no password for unlock is set, the screen goes black and device doesn't wake on pressing power button. 
I'll duplicate the issue and post a logcat asap.
